# .github/workflows/firebase-deploy.yml

name: Deploy to Firebase Functions

# 'main' 브랜치에 push 이벤트가 발생했을 때 실행됩니다.
on:
  push:
    branches:
      - main

jobs:
  deploy_functions:
    runs-on: ubuntu-latest # 워크플로우를 실행할 가상 환경
    steps:
      # 1. GitHub 저장소의 코드를 가상 환경으로 가져옵니다.
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. 프로젝트의 부품(npm 패키지)을 설치합니다.
      - name: Install dependencies
        run: npm install

      # 3. Firebase에 배포합니다. (오류 수정된 부분)
      - name: Deploy to Firebase
        uses: w9jds/firebase-action@master
        with:
          # 'action', 'project' 등의 항목을 제거하고,
          # 모든 명령어를 'args'에 통합합니다.
          args: deploy --only functions --project mansungcoin-c6e06
        env:
          # 서비스 계정 정보는 그대로 사용합니다.
          FIREBASE_credentials: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_MANSUNGCOIN_C6E06 }}

