# .github/workflows/firebase-deploy.yml

name: Deploy to Firebase Functions

# 'main' 브랜치에 push 이벤트가 발생했을 때 실행됩니다.
on:
  push:
    branches:
      - main

jobs:
  deploy_functions:
    runs-on: ubuntu-latest # 워크플로우를 실행할 가상 환경
    steps:
      # 1. GitHub 저장소의 코드를 가상 환경으로 가져옵니다.
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. 프로젝트의 부품(npm 패키지)을 설치합니다.
      - name: Install dependencies
        run: npm install

      # 3. Firebase에 배포합니다. (시크릿 이름 오류 수정)
      - name: Deploy to Firebase
        uses: w9jds/firebase-action@master
        with:
          args: deploy --only functions --project mansungcoin-c6e06
        env:
          # GitHub에 저장된 시크릿 이름을 정확히 사용하도록 수정합니다.
          # 선생님께서 만드신 'FIREBASE_JSON'을 사용합니다.
          GCP_SA_KEY: ${{ secrets.FIREBASE_JSON }}

