# .github/workflows/firebase-deploy.yml

name: Deploy to Firebase Functions

# 'main' 브랜치에 push 이벤트가 발생했을 때 실행됩니다.
on:
  push:
    branches:
      - main

jobs:
  deploy_functions:
    runs-on: ubuntu-latest # 워크플로우를 실행할 가상 환경
    steps:
      # 1. GitHub 저장소의 코드를 가상 환경으로 가져옵니다.
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. 프로젝트의 부품(npm 패키지)을 설치합니다.
      # (기존 'cd functions' 명령어를 제거하여 루트에서 바로 실행)
      - name: Install dependencies
        run: npm install

      # 3. Firebase에 배포합니다.
      - name: Deploy to Firebase
        uses: w9jds/firebase-action@master
        with:
          action: deploy
          project: 'mansungcoin-c6e06' # 선생님의 Firebase 프로젝트 ID
          token: ${{ secrets.FIREBASE_TOKEN }} # GitHub Secrets에 저장된 인증 토큰
          args: --only functions # functions만 배포합니다.
        env:
          # 서비스 계정 정보를 환경 변수로 설정합니다.
          FIREBASE_credentials: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_MANSUNGCOIN_C6E06 }}

